const fudalist = [
    { no: 1, poet: "<div class='poet'><ruby>天智天皇<rt>てんじてんのう</rt></ruby></div>", normal: "./torifuda/tori_1.png", reverse: "./torifuda/tori_r_1.png"},
    { no: 2, poet: "<div class='poet'><ruby>持統天皇<rt>じとうてんのう</rt></ruby></div>", normal: "./torifuda/tori_2.png", reverse: "./torifuda/tori_r_2.png"},
    { no: 3, poet: "<div class='poet'><ruby>柿本人麻呂<rt>かきのもとのひとまろ</rt></ruby></div>", normal: "./torifuda/tori_3.png", reverse: "./torifuda/tori_r_3.png"},
    { no: 4, poet: "<div class='poet'><ruby>山部赤人<rt>やまべのあかひと</rt></ruby></div>", normal: "./torifuda/tori_4.png", reverse: "./torifuda/tori_r_4.png"},
    { no: 5, poet: "<div class='poet'><ruby>猿丸太夫<rt>さるまるだゆう</rt></ruby></div>", normal: "./torifuda/tori_5.png", reverse: "./torifuda/tori_r_5.png"},
    { no: 6, poet: "<div class='poet'><ruby>中納言家持<rt>ちゅうなごんやかもち</rt></ruby></div><div class='poet'>(<ruby>大伴家持<rt>おおとものやかもち</rt></ruby>)</div>", normal: "./torifuda/tori_6.png", reverse: "./torifuda/tori_r_6.png"},
    { no: 7, poet: "<div class='poet'><ruby>阿倍仲麻呂<rt>あべのなかまろ</rt></ruby></div>", normal: "./torifuda/tori_7.png", reverse: "./torifuda/tori_r_7.png"},
    { no: 8, poet: "<div class='poet'><ruby>喜撰法師<rt>きせんほうし</rt></ruby></div>", normal: "./torifuda/tori_8.png", reverse: "./torifuda/tori_r_8.png"},
    { no: 9, poet: "<div class='poet'><ruby>小野小町<rt>おののこまち</rt></ruby></div>", normal: "./torifuda/tori_9.png", reverse: "./torifuda/tori_r_9.png"},
    { no: 10, poet: "<div class='poet'><ruby>蝉丸<rt>せみまる</rt></ruby></div>", normal: "./torifuda/tori_10.png", reverse: "./torifuda/tori_r_10.png"},
    { no: 11, poet: "<div class='poet'><ruby>参議篁<rt>さんぎたかむら</rt></ruby></div><div class='poet'>(<ruby>小野篁<rt>おののたかむら</rt></ruby>)</div>", normal: "./torifuda/tori_11.png", reverse: "./torifuda/tori_r_11.png"},
    { no: 12, poet: "<div class='poet'><ruby>僧正遍昭<rt>そうじょうへんじょう</rt></ruby></div>", normal: "./torifuda/tori_12.png", reverse: "./torifuda/tori_r_12.png"},
    { no: 13, poet: "<div class='poet'><ruby>陽成院<rt>ようぜいいん</rt></ruby></div><div class='poet'>(<ruby>陽成天皇<rt>ようぜいてんのう</rt></ruby>)</div>", normal: "./torifuda/tori_13.png", reverse: "./torifuda/tori_r_13.png"},
    { no: 14, poet: "<div class='poet'><ruby>河原左大臣<rt>かわらのさだいじん</rt></ruby></div><div class='poet'>(<ruby>源融<rt>みなもとのとおる</rt></ruby>)</div>", normal: "./torifuda/tori_14.png", reverse: "./torifuda/tori_r_14.png"},
    { no: 15, poet: "<div class='poet'><ruby>光孝天皇<rt>こうこうてんのう</rt></ruby></div>", normal: "./torifuda/tori_15.png", reverse: "./torifuda/tori_r_15.png"},
    { no: 16, poet: "<div class='poet'><ruby>中納言行平<rt>ちゅうなごんゆきひら</rt></ruby></div><div class='poet'>(<ruby>在原行平<rt>ありわらのゆきひら</rt></ruby>)</div>", normal: "./torifuda/tori_16.png", reverse: "./torifuda/tori_r_16.png"},
    { no: 17, poet: "<div class='poet'><ruby>在原業平朝臣<rt>ありわらのなりひらあそん</rt></ruby></div>", normal: "./torifuda/tori_17.png", reverse: "./torifuda/tori_r_17.png"},
    { no: 18, poet: "<div class='poet'><ruby>藤原敏行朝臣<rt>ふじわらのとしゆきあそん</rt></ruby></div>", normal: "./torifuda/tori_18.png", reverse: "./torifuda/tori_r_18.png"},
    { no: 19, poet: "<div class='poet'><ruby>伊勢<rt>いせ</rt></ruby></div>", normal: "./torifuda/tori_19.png", reverse: "./torifuda/tori_r_19.png"},
    { no: 20, poet: "<div class='poet'><ruby>元良親王<rt>もとよししんのう</rt></ruby></div>", normal: "./torifuda/tori_20.png", reverse: "./torifuda/tori_r_20.png"},
    { no: 21, poet: "<div class='poet'><ruby>素性法師<rt>そせいほうし</rt></ruby></div>", normal: "./torifuda/tori_21.png", reverse: "./torifuda/tori_r_21.png"},
    { no: 22, poet: "<div class='poet'><ruby>文屋康秀<rt>ふんやのやすひで</rt></ruby></div>", normal: "./torifuda/tori_22.png", reverse: "./torifuda/tori_r_22.png"},
    { no: 23, poet: "<div class='poet'><ruby>大江千里<rt>おおえのちさと</rt></ruby></div>", normal: "./torifuda/tori_23.png", reverse: "./torifuda/tori_r_23.png"},
    { no: 24, poet: "<div class='poet'><ruby>菅家<rt>かんけ</rt></ruby></div><div class='poet'>(<ruby>菅原道真<rt>すがわらのみちざね</rt></ruby>)</div>", normal: "./torifuda/tori_24.png", reverse: "./torifuda/tori_r_24.png"},
    { no: 25, poet: "<div class='poet'><ruby>三条右大臣<rt>さんじょうのうだいじん</rt></ruby></div><div class='poet'>(<ruby>藤原定方<rt>ふじわらのさだかた</rt></ruby>)</div>", normal: "./torifuda/tori_25.png", reverse: "./torifuda/tori_r_25.png"},
    { no: 26, poet: "<div class='poet'><ruby>貞信公<rt>ていしんこう</rt></ruby></div><div class='poet'>(<ruby>藤原忠平<rt>ふじわらのただひら</rt></ruby>)</div>", normal: "./torifuda/tori_26.png", reverse: "./torifuda/tori_r_26.png"},
    { no: 27, poet: "<div class='poet'><ruby>中納言兼輔<rt>ちゅうなごんかねすけ</rt></ruby></div><div class='poet'>(<ruby>藤原兼輔<rt>ふじわらのかねすけ</rt></ruby>)</div>", normal: "./torifuda/tori_27.png", reverse: "./torifuda/tori_r_27.png"},
    { no: 28, poet: "<div class='poet'><ruby>源宗行朝臣<rt>みなもとのむねゆきあそん</rt></ruby></div>", normal: "./torifuda/tori_28.png", reverse: "./torifuda/tori_r_28.png"},
    { no: 29, poet: "<div class='poet'><ruby>凡河内躬恒<rt>おおしこうちのみつね</rt></ruby></div>", normal: "./torifuda/tori_29.png", reverse: "./torifuda/tori_r_29.png"},
    { no: 30, poet: "<div class='poet'><ruby>壬生忠岑<rt>みぶのただみね</rt></ruby></div>", normal: "./torifuda/tori_30.png", reverse: "./torifuda/tori_r_30.png"},
    { no: 31, poet: "<div class='poet'><ruby>坂上是則<rt>さかのうえのこれのり</rt></ruby></div>", normal: "./torifuda/tori_31.png", reverse: "./torifuda/tori_r_31.png"},
    { no: 32, poet: "<div class='poet'><ruby>春道列樹<rt>はるみちのつらき</rt></ruby></div>", normal: "./torifuda/tori_32.png", reverse: "./torifuda/tori_r_32.png"},
    { no: 33, poet: "<div class='poet'><ruby>紀友則<rt>きのとものり</rt></ruby></div>", normal: "./torifuda/tori_33.png", reverse: "./torifuda/tori_r_33.png"},
    { no: 34, poet: "<div class='poet'><ruby>藤原興風<rt>ふじわらのおきかぜ</rt></ruby></div>", normal: "./torifuda/tori_34.png", reverse: "./torifuda/tori_r_34.png"},
    { no: 35, poet: "<div class='poet'><ruby>紀貫之<rt>きのつらゆき</rt></ruby></div>", normal: "./torifuda/tori_35.png", reverse: "./torifuda/tori_r_35.png"},
    { no: 36, poet: "<div class='poet'><ruby>清原深養父<rt>きよはらのふかやぶ</rt></ruby></div>", normal: "./torifuda/tori_36.png", reverse: "./torifuda/tori_r_36.png"},
    { no: 37, poet: "<div class='poet'><ruby>文屋朝康<rt>ふんやのあさやす</rt></ruby></div>", normal: "./torifuda/tori_37.png", reverse: "./torifuda/tori_r_37.png"},
    { no: 38, poet: "<div class='poet'><ruby>右近<rt>うこん</rt></ruby></div>", normal: "./torifuda/tori_38.png", reverse: "./torifuda/tori_r_38.png"},
    { no: 39, poet: "<div class='poet'><ruby>参議等<rt>さんぎひとし</rt></ruby></div><div class='poet'>(<ruby>源等<rt>みなもとのひとし</rt></ruby>)</div>", normal: "./torifuda/tori_39.png", reverse: "./torifuda/tori_r_39.png"},
    { no: 40, poet: "<div class='poet'><ruby>平兼盛<rt>たいらのかねもり</rt></ruby></div>", normal: "./torifuda/tori_40.png", reverse: "./torifuda/tori_r_40.png"},
    { no: 41, poet: "<div class='poet'><ruby>壬生忠見<rt>みぶのただみ</rt></ruby></div>", normal: "./torifuda/tori_41.png", reverse: "./torifuda/tori_r_41.png"},
    { no: 42, poet: "<div class='poet'><ruby>清原元輔<rt>きよはらのもとすけ</rt></ruby></div>", normal: "./torifuda/tori_42.png", reverse: "./torifuda/tori_r_42.png"},
    { no: 43, poet: "<div class='poet'><ruby>権中納言敦忠<rt>ごんちゅうなごんあつただ</rt></ruby></div><div class='poet'>(<ruby>藤原敦忠<rt>ふじわらのあつただ</rt></ruby>)</div>", normal: "./torifuda/tori_43.png", reverse: "./torifuda/tori_r_43.png"},
    { no: 44, poet: "<div class='poet'><ruby>中納言朝忠<rt>ちゅうなごんあさただ</rt></ruby></div><div class='poet'>(<ruby>藤原朝忠<rt>ふじわらのあさただ</rt></ruby>)</div>", normal: "./torifuda/tori_44.png", reverse: "./torifuda/tori_r_44.png"},
    { no: 45, poet: "<div class='poet'><ruby>謙徳公<rt>けんとくこう</rt></ruby></div><div class='poet'>(<ruby>藤原伊尹<rt>ふじわらのこれただ</rt></ruby>)</div>", normal: "./torifuda/tori_45.png", reverse: "./torifuda/tori_r_45.png"},
    { no: 46, poet: "<div class='poet'><ruby>曽禰好忠<rt>そねのよしただ</rt></ruby></div>", normal: "./torifuda/tori_46.png", reverse: "./torifuda/tori_r_46.png"},
    { no: 47, poet: "<div class='poet'><ruby>恵慶法師<rt>えぎょうほうし</rt></ruby></div>", normal: "./torifuda/tori_47.png", reverse: "./torifuda/tori_r_47.png"},
    { no: 48, poet: "<div class='poet'><ruby>源重之<rt>みなもとのしげゆき</rt></ruby></div>", normal: "./torifuda/tori_48.png", reverse: "./torifuda/tori_r_48.png"},
    { no: 49, poet: "<div class='poet'><ruby>大中臣能宣朝臣<rt>おおなかとみのよしのぶあそん</rt></ruby></div>", normal: "./torifuda/tori_49.png", reverse: "./torifuda/tori_r_49.png"},
    { no: 50, poet: "<div class='poet'><ruby>藤原義孝<rt>ふじわらのよしたか</rt></ruby></div>", normal: "./torifuda/tori_50.png", reverse: "./torifuda/tori_r_50.png"},
    { no: 51, poet: "<div class='poet'><ruby>藤原実方朝臣<rt>ふじわらのさねかたあそん</rt></ruby></div>", normal: "./torifuda/tori_51.png", reverse: "./torifuda/tori_r_51.png"},
    { no: 52, poet: "<div class='poet'><ruby>藤原道信朝臣<rt>ふじわらのみちのぶあそん</rt></ruby></div>", normal: "./torifuda/tori_52.png", reverse: "./torifuda/tori_r_52.png"},
    { no: 53, poet: "<div class='poet'><ruby>右大将道綱母<rt>うだいしょうみちつなのはは</rt></ruby></div><div class='poet'>(<ruby>藤原道綱母<rt>ふじわらのみちつなのはは</rt></ruby>)</div>", normal: "./torifuda/tori_53.png", reverse: "./torifuda/tori_r_53.png"},
    { no: 54, poet: "<div class='poet'><ruby>儀同三司母<rt>ぎどうさんしのはは</rt></ruby></div><div class='poet'>(<ruby>高階貴子<rt>たかしなのたかこ</rt></ruby>)</div>", normal: "./torifuda/tori_54.png", reverse: "./torifuda/tori_r_54.png"},
    { no: 55, poet: "<div class='poet'><ruby>大納言公任<rt>だいなごんきんとう</rt></ruby></div><div class='poet'>(<ruby>藤原公任<rt>ふじわらのきんとう</rt></ruby>)</div>", normal: "./torifuda/tori_55.png", reverse: "./torifuda/tori_r_55.png"},
    { no: 56, poet: "<div class='poet'><ruby>和泉式部<rt>いずみしきぶ</rt></ruby></div>", normal: "./torifuda/tori_56.png", reverse: "./torifuda/tori_r_56.png"},
    { no: 57, poet: "<div class='poet'><ruby>紫式部<rt>むらさきしきぶ</rt></ruby></div>", normal: "./torifuda/tori_57.png", reverse: "./torifuda/tori_r_57.png"},
    { no: 58, poet: "<div class='poet'><ruby>大弐三位<rt>だいにのさんみ</rt></ruby></div>", normal: "./torifuda/tori_58.png", reverse: "./torifuda/tori_r_58.png"},
    { no: 59, poet: "<div class='poet'><ruby>赤染衛門<rt>あかぞめえもん</rt></ruby></div>", normal: "./torifuda/tori_59.png", reverse: "./torifuda/tori_r_59.png"},
    { no: 60, poet: "<div class='poet'><ruby>小式部内侍<rt>こしきぶのないし</rt></ruby></div>", normal: "./torifuda/tori_60.png", reverse: "./torifuda/tori_r_60.png"},
    { no: 61, poet: "<div class='poet'><ruby>伊勢大輔<rt>いせのたいふ</rt></ruby></div>", normal: "./torifuda/tori_61.png", reverse: "./torifuda/tori_r_61.png"},
    { no: 62, poet: "<div class='poet'><ruby>清少納言<rt>せいしょうなごん</rt></ruby></div>", normal: "./torifuda/tori_62.png", reverse: "./torifuda/tori_r_62.png"},
    { no: 63, poet: "<div class='poet'><ruby>左京大夫道雅<rt>さきょうのだいぶみちまさ</rt></ruby></div><div class='poet'>(<ruby>藤原道雅<rt>ふじわらのみちまさ</rt></ruby>)</div>", normal: "./torifuda/tori_63.png", reverse: "./torifuda/tori_r_63.png"},
    { no: 64, poet: "<div class='poet'><ruby>権中納言定頼<rt>ごんちゅうなごんさだより</rt></ruby></div><div class='poet'>(<ruby>藤原定頼<rt>ふじわらのさだより</rt></ruby>)</div>", normal: "./torifuda/tori_64.png", reverse: "./torifuda/tori_r_64.png"},
    { no: 65, poet: "<div class='poet'><ruby>相模<rt>さがみ</rt></ruby></div>", normal: "./torifuda/tori_65.png", reverse: "./torifuda/tori_r_65.png"},
    { no: 66, poet: "<div class='poet'><ruby>前大僧正行尊<rt>さきのだいそうじょうぎょうそん</rt></ruby></div>", normal: "./torifuda/tori_66.png", reverse: "./torifuda/tori_r_66.png"},
    { no: 67, poet: "<div class='poet'><ruby>周防内侍<rt>すおうのないし</rt></ruby></div>", normal: "./torifuda/tori_67.png", reverse: "./torifuda/tori_r_67.png"},
    { no: 68, poet: "<div class='poet'><ruby>三条院<rt>さんじょういん</rt></ruby></div><div class='poet'>(<ruby>三条天皇<rt>さんじょうてんのう</rt></ruby>)</div>", normal: "./torifuda/tori_68.png", reverse: "./torifuda/tori_r_68.png"},
    { no: 69, poet: "<div class='poet'><ruby>能因法師<rt>のういんほうし</rt></ruby></div>", normal: "./torifuda/tori_69.png", reverse: "./torifuda/tori_r_69.png"},
    { no: 70, poet: "<div class='poet'><ruby>良選法師<rt>りょうぜんほうし</rt></ruby></div>", normal: "./torifuda/tori_70.png", reverse: "./torifuda/tori_r_70.png"},
    { no: 71, poet: "<div class='poet'><ruby>大納言経信<rt>だいなごんつねのぶ</rt></ruby></div><div class='poet'>(<ruby>源経信<rt>みなもとのつねのぶ</rt></ruby>)</div>", normal: "./torifuda/tori_71.png", reverse: "./torifuda/tori_r_71.png"},
    { no: 72, poet: "<div class='poet'><ruby>祐子内親王家紀伊<rt>ゆうしないしんのうけのきい</rt></ruby></div>", normal: "./torifuda/tori_72.png", reverse: "./torifuda/tori_r_72.png"},
    { no: 73, poet: "<div class='poet'><ruby>前権中納言匡房<rt>さきのごんちゅうなごんまさふさ</rt></ruby></div><div class='poet'>(<ruby>大江匡房<rt>おおえのまさふさ</rt></ruby>)</div>", normal: "./torifuda/tori_73.png", reverse: "./torifuda/tori_r_73.png"},
    { no: 74, poet: "<div class='poet'><ruby>源俊頼朝臣<rt>みなもとのとしよりあそん</rt></ruby></div>", normal: "./torifuda/tori_74.png", reverse: "./torifuda/tori_r_74.png"},
    { no: 75, poet: "<div class='poet'><ruby>藤原基俊<rt>ふじわらのもととし</rt></ruby></div>", normal: "./torifuda/tori_75.png", reverse: "./torifuda/tori_r_75.png"},
    { no: 76, poet: "<div class='poet'><ruby>法性寺入道前関白太政大臣<rt>ほっしょうじにゅうどうさきのかんぱくだじょうだいじん</rt></ruby></div><div class='poet'>(<ruby>藤原忠通<rt>ふじわらのただみち</rt></ruby>)</div>", normal: "./torifuda/tori_76.png", reverse: "./torifuda/tori_r_76.png"},
    { no: 77, poet: "<div class='poet'><ruby>崇徳院<rt>すとくいん</rt></ruby></div><div class='poet'>(<ruby>崇徳天皇<rt>すとくてんのう</rt></ruby>)</div>", normal: "./torifuda/tori_77.png", reverse: "./torifuda/tori_r_77.png"},
    { no: 78, poet: "<div class='poet'><ruby>源兼昌<rt>みなもとのかねまさ</rt></ruby></div>", normal: "./torifuda/tori_78.png", reverse: "./torifuda/tori_r_78.png"},
    { no: 79, poet: "<div class='poet'><ruby>左京大夫顕輔<rt>さきょうのだいぶあきすけ</rt></ruby></div><div class='poet'>(<ruby>藤原顕輔<rt>ふじわらのあきすけ</rt></ruby>)</div>", normal: "./torifuda/tori_79.png", reverse: "./torifuda/tori_r_79.png"},
    { no: 80, poet: "<div class='poet'><ruby>待賢門院堀河<rt>たいけんもんいんのほりかわ</rt></ruby></div>", normal: "./torifuda/tori_80.png", reverse: "./torifuda/tori_r_80.png"},
    { no: 81, poet: "<div class='poet'><ruby>後徳大寺左大臣<rt>ごとくだいじのさだいじん</rt></ruby></div><div class='poet'>(<ruby>徳大寺実定<rt>とくだいじさねさだ</rt></ruby>)</div>", normal: "./torifuda/tori_81.png", reverse: "./torifuda/tori_r_81.png"},
    { no: 82, poet: "<div class='poet'><ruby>道因法師<rt>どういんほうし</rt></ruby></div><div class='poet'>(<ruby>藤原敦頼<rt>ふじわらのあつより</rt></ruby>)</div>", normal: "./torifuda/tori_82.png", reverse: "./torifuda/tori_r_82.png"},
    { no: 83, poet: "<div class='poet'><ruby>皇太后宮大夫俊成<rt>こうたいごうぐうのだいぶしゅんぜい</rt></ruby></div><div class='poet'>(<ruby>藤原俊成<rt>ふじわらのしゅんぜい</rt></ruby>)</div>", normal: "./torifuda/tori_83.png", reverse: "./torifuda/tori_r_83.png"},
    { no: 84, poet: "<div class='poet'><ruby>藤原清輔朝臣<rt>ふじわらのきよすけあそん</rt></ruby></div>", normal: "./torifuda/tori_84.png", reverse: "./torifuda/tori_r_84.png"},
    { no: 85, poet: "<div class='poet'><ruby>俊恵法師<rt>しゅんえほうし</rt></ruby></div>", normal: "./torifuda/tori_85.png", reverse: "./torifuda/tori_r_85.png"},
    { no: 86, poet: "<div class='poet'><ruby>西行法師<rt>さいぎょうほうし</rt></ruby></div>", normal: "./torifuda/tori_86.png", reverse: "./torifuda/tori_r_86.png"},
    { no: 87, poet: "<div class='poet'><ruby>寂蓮法師<rt>じゃくれんほうし</rt></ruby></div>", normal: "./torifuda/tori_87.png", reverse: "./torifuda/tori_r_87.png"},
    { no: 88, poet: "<div class='poet'><ruby>皇嘉門院別当<rt>こうかもんいんのべっとう</rt></ruby></div>", normal: "./torifuda/tori_88.png", reverse: "./torifuda/tori_r_88.png"},
    { no: 89, poet: "<div class='poet'><ruby>式子内親王<rt>しょくしないしんのう</rt></ruby></div>", normal: "./torifuda/tori_89.png", reverse: "./torifuda/tori_r_89.png"},
    { no: 90, poet: "<div class='poet'><ruby>殷富門院大輔<rt>いんぷもんいんのたいふ</rt></ruby></div>", normal: "./torifuda/tori_90.png", reverse: "./torifuda/tori_r_90.png"},
    { no: 91, poet: "<div class='poet'><ruby>後京極摂政前太政大臣<rt>ごきょうごくせっしょうさきのだじょうだいじん</rt></ruby></div><div class='poet'>(<ruby>九条良経<rt>くじょうよしつね</rt></ruby>)</div>", normal: "./torifuda/tori_91.png", reverse: "./torifuda/tori_r_91.png"},
    { no: 92, poet: "<div class='poet'><ruby>二条院讃岐<rt>にじょういんのさぬき</rt></ruby></div>", normal: "./torifuda/tori_92.png", reverse: "./torifuda/tori_r_92.png"},
    { no: 93, poet: "<div class='poet'><ruby>鎌倉右大臣<rt>かまくらのうだいじん</rt></ruby></div><div class='poet'>(<ruby>源実朝<rt>みなもとのさねとも</rt></ruby>)</div>", normal: "./torifuda/tori_93.png", reverse: "./torifuda/tori_r_93.png"},
    { no: 94, poet: "<div class='poet'><ruby>参議雅経<rt>さんぎまさつね</rt></ruby></div><div class='poet'>(<ruby>飛鳥井雅経<rt>あすかいまさつね</rt></ruby>)</div>", normal: "./torifuda/tori_94.png", reverse: "./torifuda/tori_r_94.png"},
    { no: 95, poet: "<div class='poet'><ruby>前大僧正慈円<rt>さきのだいそうじょうじえん</rt></ruby></div>", normal: "./torifuda/tori_95.png", reverse: "./torifuda/tori_r_95.png"},
    { no: 96, poet: "<div class='poet'><ruby>入道前太政大臣<rt>にゅうどうさきのだじょうだいじん</rt></ruby></div><div class='poet'>(<ruby>西園寺公経<rt>さいおんじきんつね</rt></ruby>)</div>", normal: "./torifuda/tori_96.png", reverse: "./torifuda/tori_r_96.png"},
    { no: 97, poet: "<div class='poet'><ruby>権中納言定家<rt>ごんちゅうなごんていか</rt></ruby></div><div class='poet'>(<ruby>藤原定家<rt>ふじわらのていか</rt></ruby>)</div>", normal: "./torifuda/tori_97.png", reverse: "./torifuda/tori_r_97.png"},
    { no: 98, poet: "<div class='poet'><ruby>従二位家隆<rt>じゅにいのいえたか</rt></ruby></div><div class='poet'>(<ruby>藤原家隆<rt>ふじわらのいえたか</rt></ruby>)</div>", normal: "./torifuda/tori_98.png", reverse: "./torifuda/tori_r_98.png"},
    { no: 99, poet: "<div class='poet'><ruby>後鳥羽院<rt>ごとばいん</rt></ruby></div><div class='poet'>(<ruby>後鳥羽天皇<rt>ごとばてんのう</rt></ruby>)</div>", normal: "./torifuda/tori_99.png", reverse: "./torifuda/tori_r_99.png"},
    { no: 100, poet: "<div class='poet'><ruby>順徳院<rt>じゅんとくいん</rt></ruby></div><div class='poet'>(<ruby>順徳天皇<rt>じゅんとくてんのう</rt></ruby>)</div>", normal: "./torifuda/tori_100.png", reverse: "./torifuda/tori_r_100.png"}
]